version: "3"
services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  php:
    build: ./docker/php
    container_name: ${PROJECT_NAME}-php
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini /usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - php
    ports:
      - "80:8000"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    env_file: .env
    depends_on:
      - db
    ports:
      - 3002:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  bs:
    image: ustwo/browser-sync
    container_name: ${PROJECT_NAME}-bs
    command: start --proxy "nginx:8000" --files "app/**/*.php,app/**/*.css,app/**/*.js"
    volumes:
      - ./app:/source/app
    depends_on:
      - nginx
    ports:
      - "3000:3000"
      - "3001:3001"

  webpack:
    build: ./docker/webpack
    container_name: ${PROJECT_NAME}-webpack
    volumes:
      - ./src:/webpack/src
      - ./app:/webpack/app
      - ./docker/webpack/package.json:/webpack/package.json
      - ./docker/webpack/webpack.config.js:/webpack/webpack.config.js
      - ./docker/webpack/.eslintrc.js:/webpack/.eslintrc.js
