version: "3"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file: .env
    ports:
      - 3307:3306

  app:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    depends_on:
      - mysql
    ports:
      - 3002:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  bs:
    image: ustwo/browser-sync
    command: start --proxy "nginx:8000" --files "app/**/*.php,app/**/*.css,app/**/*.js"
    volumes:
      - ./app:/source/app
    depends_on:
      - nginx
    ports:
      - 3000:3000
      - 3001:3001

  webpack:
    build: ./docker/webpack
    volumes:
      - ./src:/webpack/src
      - ./app:/webpack/app
      - ./docker/webpack/package.json:/webpack/package.json
      - ./docker/webpack/webpack.config.js:/webpack/webpack.config.js
